### ISSUE TITLE
Snapshot GraphQL Mutation

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-server#12]
Create 
- [ ] Schema for Snapshot Mutation
- [ ] SQL query to save data in new db format
- [ ] SQL query to save data in old db format

Epic #24

**Comment by pA1nD** [comment]
This mutation should store the data twice (in two formats). 
IMPORTANT: Indicate in the old survey, that the duplicated data is duplicated (as there's still data created via the old endpoint and we need to keep track of which data we have to migrate over afterwards without porting over the data that's lready stored in the new format).

There are spreadsheets available that explain which keys exist for a survey and which elements are only available in the new one (they don't have to be saved in the old format):
https://drive.google.com/drive/u/0/folders/1zSWrwGZx9ULD0vfl5s-Rpcd04zKsOviZ

The simple one priority is to have an endpoint saving the data in the new fomat 
AND for the keys defined in those documents (link provided above) also in the old format.

**Comment by gigerbytes** [comment]
New issue at #24
