### ISSUE TITLE
Show lifemaps from the mobile app in the web app

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/stoplight-server#15]
As a user I want to see the lifemaps that were created using the mobile app in the web app to make sure, my data is there and to use the reporting functionality.

**Comment by gigerbytes** [comment]
#16 data only validated for UK survey.

Socio economic questions of the other surveys still have to be added to the mapping objects in the script.

**Comment by pA1nD** [comment]
seems to work (Y)

**Comment by gigerbytes** [comment]
Note: Reporting functionality:

Filtering works
CSV download does not work

**Comment by stacylorraineprendeville** [comment]
In testing environment as well

**Comment by gigerbytes** [comment]
Now deployed in testing.

**Comment by gigerbytes** [comment]
@pA1nD  please check if deployed to testing.
