### ISSUE TITLE
Accept Snapshots from app

### ISSUE THREAD

**Issue by gigiroyg** [FundacionParaguaya/stoplight-server#24]
AddSnapshot:

### Specification
- Accepts a mutation with the snapshot information
    - Survey ID
    - Family Answers
    - SocioEconomic Answers
    - Stoplight Indicator Answers
    - Priority & Achievments Answers

### Functionality
- Save Family Information
    1. Save `family` record
    2. Save `family_members` records

- Save Snapshot Information
    1. Create`snapshot` record
    2. Create `snapshot_economic` record
    3. Create `snapshot_economic_member` records
    4. Create `snapshot_stoplight` record
    5. Create `snapshot_stoplight_priority` and `snapshot_stoplight_achievement` records

It is important that the family_id is matched in the `snapshot` record

Epic #19

**Comment by gigerbytes** [comment]
We should use [postgraphile](https://www.graphile.org/postgraphile/)

See this: https://www.youtube.com/watch?v=b3pwlCDy6vY (7 mins)
