### ISSUE TITLE
EndPoint: EditSurvey

### ISSUE THREAD

**Issue by gigiroyg** [FundacionParaguaya/stoplight-server#27]
Edit an already existing survey definition.

### Specification
Given an existing survey, the user may update it and provide information below
1. Title
2. Description
3. SocioEconomic Details
4. Stoplight Indicators

The following details cannot be edited:
1. Org Id
2. Hub Id

Survey is a JSON that is sent as a mutation, with the referenced Survey ID to match

### Functionality
- [ ] It creates a new survey_version and

1. Sets the current field of the old survey version to false
2. Sets the current field of the newly created version to true
3. `version` is incremented

- [ ] It creates a new survey_definition and

1. Sets the active field of the old survey definition to false
2. Sets the active field of the newly created definition to true

Epic #20

**Comment by gigerbytes** [comment]
Functionality may require editing the socio economic data as well. Might not be so easy to edit a family without affecting other tables. Needs further investigation.
