### ISSUE TITLE
Connect NodeJs to PostGreSQL database

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-server#3]
Connect the Node server to the postgres database

### Acceptance Criteria
- [x] Create a config file to connect to database in a clean way
- [x] Be able to query data
- [ ] Be able to write data
- [ ] Test coverage

Epic #1

**Comment by stacylorraineprendeville** [comment]
@pA1nD can you assign it please

**Comment by pA1nD** [comment]
@gigerbytes I can't see the tests for this.
