### ISSUE TITLE
Provide `/graphql` endpoint

### ISSUE THREAD

**Issue by gigerbytes** [FundacionParaguaya/stoplight-server#4]
Provide a /graphql endpoint that can be used by the client to send queries & mutations\

- [x] queries
- [ ] mutations

Epic #1

**Comment by stacylorraineprendeville** [comment]
@pA1nD If you have added this to in progress can you assign it please - really anything in progress needs to be assigned to a sprint...

**Comment by stacylorraineprendeville** [comment]
Bjorn wants to close
